name: Deploy to Azure VM (OpenSSH, No Registry, Compose)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

env:
  APP_DIR: /opt/apps/testing
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key & known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY:  ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_vm
          chmod 600 ~/.ssh/id_vm
          # Pin server keys into known_hosts (ed25519,rsa,ecdsa)
          ssh-keyscan -H -t ed25519,rsa,ecdsa "$SSH_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh-keygen -lf ~/.ssh/known_hosts || true

      - name: Prepare remote dir (and ensure rsync)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -i ~/.ssh/id_vm -p "${{ secrets.SSH_PORT || 22 }}" -o StrictHostKeyChecking=yes \
            "$SSH_USER@$SSH_HOST" "
              set -e
              sudo apt-get update -y >/dev/null 2>&1 || true
              sudo apt-get install -y rsync >/dev/null 2>&1 || true
              sudo mkdir -p '${APP_DIR}'
              sudo chown -R \$USER:\$USER '${APP_DIR}'
              rm -rf '${APP_DIR}'/*
            "

      - name: Upload repo (rsync over SSH)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          rm -rf .git .github || true
          rsync -az --delete -e "ssh -i ~/.ssh/id_vm -p ${{ secrets.SSH_PORT || 22 }} -o StrictHostKeyChecking=yes" \
            ./ "$SSH_USER@$SSH_HOST:${APP_DIR}/"

      - name: Build & start (Docker Compose if present)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -i ~/.ssh/id_vm -p "${{ secrets.SSH_PORT || 22 }}" -o StrictHostKeyChecking=yes \
            "$SSH_USER@$SSH_HOST" "
              set -e
              # Install Docker if missing
              if ! command -v docker >/dev/null 2>&1; then
                curl -fsSL https://get.docker.com | sh
                sudo systemctl enable --now docker
              fi
              # Ensure compose plugin
              if ! sudo docker compose version >/dev/null 2>&1; then
                sudo apt-get update -y
                sudo apt-get install -y docker-compose-plugin
              fi

              cd '${APP_DIR}'
              [ -f .env ] || { [ -f .env.example ] && cp .env.example .env; } || true

              if [ -f docker-compose.yml ] || [ -f docker-compose.yaml ]; then
                # Use Compose (project name = repo name)
                sudo docker compose -p '${PROJECT_NAME}' down --remove-orphans
                sudo docker compose -p '${PROJECT_NAME}' up -d --build --remove-orphans
              else
                # Fallback: single Dockerfile (requires APP_NAME/PUBLIC_PORT/CONTAINER_PORT secrets)
                SHORT_SHA=$(echo '${{ github.sha }}' | cut -c1-7)
                APP='${{ secrets.APP_NAME }}'
                PUB='${{ secrets.PUBLIC_PORT }}'
                INN='${{ secrets.CONTAINER_PORT }}'
                [ -n \"$APP\" ] && [ -n \"$PUB\" ] && [ -n \"$INN\" ] || { echo 'Missing APP_NAME/PUBLIC_PORT/CONTAINER_PORT'; exit 1; }
                sudo docker build -t \"$APP:$SHORT_SHA\" -t \"$APP:latest\" .
                sudo docker rm -f \"$APP\" 2>/dev/null || true
                sudo docker run -d --name \"$APP\" -p \"$PUB:$INN\" --restart=always \"$APP:latest\"
              fi

              sudo docker image prune -f
            "
